name: Setup environment
description: Common environment setup steps for all workflows
inputs:
  jdk:
    description: Set up JDK
    required: false
    default: 'true'
  gradle:
    description: Set up Gradle
    required: false
    default: 'true'
runs:
  using: composite
  steps:
  - name: Set up JDK
    if: ${{ inputs.jdk || inputs.gradle }}
    uses: actions/setup-java@v4
    with:
      java-version: '17'
      distribution: 'temurin'
      # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
      # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
  - name: Set up Gradle
    if: ${{ inputs.gradle }}
    uses: gradle/gradle-build-action@v3
